### PR TITLE
Add Python3 and Unicode support

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by nsoranzo** [comment]
Ping @jmchilton

**Comment by nsoranzo** [comment]
Rebased with more changes for Unicode.

**Comment by nsoranzo** [comment]
Ping @jmchilton

**Comment by jmchilton** [comment]
Can someone give me (jmchilton on PyPI) or @nsoranzo access to publish this to PyPI (ping @jxtx , @natefoo @davebx )?

**Comment by nsoranzo** [comment]
Ping @jxtx @natefoo @davebx

**Comment by natefoo** [comment]
@jmchilton you've been added, @nsoranzo I am happy to add you as well if you have a PyPI account (I don't see a way to search and I didn't want to assume).

**Comment by nsoranzo** [comment]
You would probably have guessed right, I'm `nsoranzo` on PyPI too.

**Comment by natefoo** [comment]
I figured, but who knows, there could be a doppelgänger N. Soranzo over there on PyPI. ;D

You've been added as well.

**Comment by nsoranzo** [comment]
Thanks @natefoo, I've made the new 0.4.3 release on PyPI.

**Pull request merged**
